// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyKhachSan.Models;

#nullable disable

namespace QuanLyKhachSan.Migrations
{
    [DbContext(typeof(QuanLyKhachSanContext))]
    [Migration("20260422150825_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("QuanLyKhachSan.Models.ChiTietDatPhong", b =>
                {
                    b.Property<int>("MaChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_chi_tiet");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaChiTiet"));

                    b.Property<decimal>("GiaMoiDem")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("gia_moi_dem");

                    b.Property<decimal>("GiamGia")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("giam_gia");

                    b.Property<int>("MaDatPhong")
                        .HasColumnType("int")
                        .HasColumnName("ma_dat_phong");

                    b.Property<int>("MaPhong")
                        .HasColumnType("int")
                        .HasColumnName("ma_phong");

                    b.Property<uint>("SoDem")
                        .HasColumnType("int unsigned")
                        .HasColumnName("so_dem");

                    b.HasKey("MaChiTiet")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "MaPhong" }, "fk_ctdp_phong");

                    b.HasIndex(new[] { "MaDatPhong", "MaPhong" }, "ma_dat_phong")
                        .IsUnique();

                    b.ToTable("chi_tiet_dat_phong", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.DatPhong", b =>
                {
                    b.Property<int>("MaDatPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_dat_phong");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaDatPhong"));

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int")
                        .HasColumnName("ma_khach_hang");

                    b.Property<DateOnly>("NgayNhanPhong")
                        .HasColumnType("date")
                        .HasColumnName("ngay_nhan_phong");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_tao")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly>("NgayTraPhong")
                        .HasColumnType("date")
                        .HasColumnName("ngay_tra_phong");

                    b.Property<byte>("SoNguoiLon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("so_nguoi_lon")
                        .HasDefaultValueSql("'1'");

                    b.Property<byte>("SoTreEm")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("so_tre_em");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('cho_xac_nhan','da_xac_nhan','da_nhan_phong','da_tra_phong','da_huy')")
                        .HasColumnName("trang_thai")
                        .HasDefaultValueSql("'cho_xac_nhan'");

                    b.HasKey("MaDatPhong")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "MaKhachHang" }, "idx_dat_phong_khach_hang");

                    b.HasIndex(new[] { "NgayNhanPhong", "NgayTraPhong" }, "idx_dat_phong_ngay");

                    b.ToTable("dat_phong", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.DichVu", b =>
                {
                    b.Property<int>("MaDichVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_dich_vu");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaDichVu"));

                    b.Property<bool?>("DangHoatDong")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("dang_hoat_dong")
                        .HasDefaultValueSql("'1'");

                    b.Property<decimal>("DonGia")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("don_gia");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("ten_dich_vu");

                    b.HasKey("MaDichVu")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "TenDichVu" }, "ten_dich_vu")
                        .IsUnique();

                    b.ToTable("dich_vu", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.HoaDon", b =>
                {
                    b.Property<int>("MaHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_hoa_don");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaHoaDon"));

                    b.Property<decimal>("GiamGia")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("giam_gia");

                    b.Property<int>("MaDatPhong")
                        .HasColumnType("int")
                        .HasColumnName("ma_dat_phong");

                    b.Property<DateTime>("NgayLap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_lap")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("ThanhTien")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("thanh_tien");

                    b.Property<decimal>("TienThue")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("tien_thue");

                    b.Property<decimal>("TongTienDichVu")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("tong_tien_dich_vu");

                    b.Property<decimal>("TongTienPhong")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("tong_tien_phong");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('chua_thanh_toan','thanh_toan_mot_phan','da_thanh_toan')")
                        .HasColumnName("trang_thai")
                        .HasDefaultValueSql("'chua_thanh_toan'");

                    b.HasKey("MaHoaDon")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "MaDatPhong" }, "ma_dat_phong")
                        .IsUnique()
                        .HasDatabaseName("ma_dat_phong1");

                    b.ToTable("hoa_don", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.KhachHang", b =>
                {
                    b.Property<int>("MaKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_khach_hang");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaKhachHang"));

                    b.Property<string>("Email")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("email");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("ho_ten");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_tao")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("QuocTich")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("quoc_tich");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("so_dien_thoai");

                    b.Property<string>("SoGiayTo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("so_giay_to");

                    b.HasKey("MaKhachHang")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Email" }, "email")
                        .IsUnique();

                    b.HasIndex(new[] { "SoDienThoai" }, "so_dien_thoai")
                        .IsUnique();

                    b.HasIndex(new[] { "SoGiayTo" }, "so_giay_to")
                        .IsUnique();

                    b.ToTable("khach_hang", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.LoaiPhong", b =>
                {
                    b.Property<int>("MaLoaiPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_loai_phong");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaLoaiPhong"));

                    b.Property<decimal>("GiaCoBan")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("gia_co_ban");

                    b.Property<string>("MoTa")
                        .HasColumnType("text")
                        .HasColumnName("mo_ta");

                    b.Property<byte>("SucChuaToiDa")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("suc_chua_toi_da");

                    b.Property<string>("TenLoaiPhong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ten_loai_phong");

                    b.HasKey("MaLoaiPhong")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "TenLoaiPhong" }, "ten_loai_phong")
                        .IsUnique();

                    b.ToTable("loai_phong", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.Phong", b =>
                {
                    b.Property<int>("MaPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_phong");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaPhong"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ghi_chu");

                    b.Property<int>("MaLoaiPhong")
                        .HasColumnType("int")
                        .HasColumnName("ma_loai_phong");

                    b.Property<string>("SoPhong")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("so_phong");

                    b.Property<byte?>("Tang")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("tang");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('san_sang','dang_o','bao_tri')")
                        .HasColumnName("trang_thai")
                        .HasDefaultValueSql("'san_sang'");

                    b.HasKey("MaPhong")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "MaLoaiPhong" }, "fk_phong_loai_phong");

                    b.HasIndex(new[] { "TrangThai" }, "idx_phong_trang_thai");

                    b.HasIndex(new[] { "SoPhong" }, "so_phong")
                        .IsUnique();

                    b.ToTable("phong", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.SuDungDichVu", b =>
                {
                    b.Property<int>("MaSuDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_su_dung");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaSuDung"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ghi_chu");

                    b.Property<int>("MaDatPhong")
                        .HasColumnType("int")
                        .HasColumnName("ma_dat_phong");

                    b.Property<int>("MaDichVu")
                        .HasColumnType("int")
                        .HasColumnName("ma_dich_vu");

                    b.Property<uint>("SoLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("so_luong")
                        .HasDefaultValueSql("'1'");

                    b.Property<DateTime>("ThoiDiemSuDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("thoi_diem_su_dung")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("MaSuDung")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "MaDichVu" }, "fk_sddv_dich_vu");

                    b.HasIndex(new[] { "MaDatPhong" }, "idx_sddv_dat_phong");

                    b.ToTable("su_dung_dich_vu", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.TaiKhoan", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_tai_khoan");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaTaiKhoan"));

                    b.Property<string>("Email")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("email");

                    b.Property<string>("HoTenHienThi")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("ho_ten_hien_thi");

                    b.Property<DateTime?>("LanDangNhapCuoi")
                        .HasColumnType("datetime")
                        .HasColumnName("lan_dang_nhap_cuoi");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("mat_khau_hash");

                    b.Property<DateTime>("NgayCapNhat")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_cap_nhat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("NgayCapNhat"));

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_tao")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("so_dien_thoai");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ten_dang_nhap");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('hoat_dong','bi_khoa')")
                        .HasColumnName("trang_thai")
                        .HasDefaultValueSql("'hoat_dong'");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('quan_tri','quan_ly','le_tan','ke_toan')")
                        .HasColumnName("vai_tro")
                        .HasDefaultValueSql("'le_tan'");

                    b.HasKey("MaTaiKhoan")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Email" }, "email")
                        .IsUnique()
                        .HasDatabaseName("email1");

                    b.HasIndex(new[] { "TenDangNhap" }, "ten_dang_nhap")
                        .IsUnique();

                    b.ToTable("tai_khoan", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.ThanhToan", b =>
                {
                    b.Property<int>("MaThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_thanh_toan");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaThanhToan"));

                    b.Property<int>("MaHoaDon")
                        .HasColumnType("int")
                        .HasColumnName("ma_hoa_don");

                    b.Property<string>("MaThamChieu")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("ma_tham_chieu");

                    b.Property<string>("PhuongThuc")
                        .IsRequired()
                        .HasColumnType("enum('tien_mat','the','chuyen_khoan','vi_dien_tu')")
                        .HasColumnName("phuong_thuc");

                    b.Property<decimal>("SoTien")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("so_tien");

                    b.Property<DateTime>("ThoiDiemThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("thoi_diem_thanh_toan")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("MaThanhToan")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "MaHoaDon" }, "idx_thanh_toan_hoa_don");

                    b.ToTable("thanh_toan", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.ChiTietDatPhong", b =>
                {
                    b.HasOne("QuanLyKhachSan.Models.DatPhong", "MaDatPhongNavigation")
                        .WithMany("ChiTietDatPhongs")
                        .HasForeignKey("MaDatPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ctdp_dat_phong");

                    b.HasOne("QuanLyKhachSan.Models.Phong", "MaPhongNavigation")
                        .WithMany("ChiTietDatPhongs")
                        .HasForeignKey("MaPhong")
                        .IsRequired()
                        .HasConstraintName("fk_ctdp_phong");

                    b.Navigation("MaDatPhongNavigation");

                    b.Navigation("MaPhongNavigation");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.DatPhong", b =>
                {
                    b.HasOne("QuanLyKhachSan.Models.KhachHang", "MaKhachHangNavigation")
                        .WithMany("DatPhongs")
                        .HasForeignKey("MaKhachHang")
                        .IsRequired()
                        .HasConstraintName("fk_dat_phong_khach_hang");

                    b.Navigation("MaKhachHangNavigation");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.HoaDon", b =>
                {
                    b.HasOne("QuanLyKhachSan.Models.DatPhong", "MaDatPhongNavigation")
                        .WithOne("HoaDon")
                        .HasForeignKey("QuanLyKhachSan.Models.HoaDon", "MaDatPhong")
                        .IsRequired()
                        .HasConstraintName("fk_hoa_don_dat_phong");

                    b.Navigation("MaDatPhongNavigation");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.Phong", b =>
                {
                    b.HasOne("QuanLyKhachSan.Models.LoaiPhong", "MaLoaiPhongNavigation")
                        .WithMany("Phongs")
                        .HasForeignKey("MaLoaiPhong")
                        .IsRequired()
                        .HasConstraintName("fk_phong_loai_phong");

                    b.Navigation("MaLoaiPhongNavigation");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.SuDungDichVu", b =>
                {
                    b.HasOne("QuanLyKhachSan.Models.DatPhong", "MaDatPhongNavigation")
                        .WithMany("SuDungDichVus")
                        .HasForeignKey("MaDatPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sddv_dat_phong");

                    b.HasOne("QuanLyKhachSan.Models.DichVu", "MaDichVuNavigation")
                        .WithMany("SuDungDichVus")
                        .HasForeignKey("MaDichVu")
                        .IsRequired()
                        .HasConstraintName("fk_sddv_dich_vu");

                    b.Navigation("MaDatPhongNavigation");

                    b.Navigation("MaDichVuNavigation");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.ThanhToan", b =>
                {
                    b.HasOne("QuanLyKhachSan.Models.HoaDon", "MaHoaDonNavigation")
                        .WithMany("ThanhToans")
                        .HasForeignKey("MaHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_thanh_toan_hoa_don");

                    b.Navigation("MaHoaDonNavigation");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.DatPhong", b =>
                {
                    b.Navigation("ChiTietDatPhongs");

                    b.Navigation("HoaDon");

                    b.Navigation("SuDungDichVus");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.DichVu", b =>
                {
                    b.Navigation("SuDungDichVus");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.HoaDon", b =>
                {
                    b.Navigation("ThanhToans");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.KhachHang", b =>
                {
                    b.Navigation("DatPhongs");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.LoaiPhong", b =>
                {
                    b.Navigation("Phongs");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.Phong", b =>
                {
                    b.Navigation("ChiTietDatPhongs");
                });
#pragma warning restore 612, 618
        }
    }
}
